nuget pack LightNode.Core.nuspec
nuget pack LightNode.Server.nuspec
nuget pack LightNode.Client.PCL.T4.nuspec
nuget pack LightNode.Client.UniRx.T4.nuspec
nuget pack LightNode.Formatter.ProtoBuf.nuspec
nuget pack LightNode.Formatter.MsgPack.nuspec
nuget pack LightNode.Formatter.JsonNet.nuspec
nuget pack LightNode.Formatter.Jil.nuspec
nuget pack LightNode.Formatter.Jil.LZ4.nuspec