nuget push LightNode.Core.1.4.0.nupkg
nuget push LightNode.Server.1.4.0.nupkg
nuget push LightNode.Client.PCL.T4.1.4.0.nupkg
nuget push LightNode.Client.UniRx.T4.1.4.0.nupkg
nuget push LightNode.Formatter.ProtoBuf.1.4.0.nupkg
nuget push LightNode.Formatter.MsgPack.1.4.0.nupkg
nuget push LightNode.Formatter.JsonNet.1.4.0.nupkg
nuget push LightNode.Formatter.Jil.1.4.0.nupkg
nuget push LightNode.Formatter.Jil.LZ4.1.4.0.nupkg
nuget push Glimpse.LightNode.1.4.0.nupkg
nuget push LightNode.Swagger.1.4.0.nupkg
nuget push LightNode.Diagnostics.EventSource.1.4.0.nupkg